# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: greeter.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rgreeter.proto\x12\x07greeter\"\x07\n\x05\x45mpty\"\x1d\n\nHelloReply\x12\x0f\n\x07message\x18\x01 \x01(\t2<\n\x07Greeter\x12\x31\n\x08Greeting\x12\x0e.greeter.Empty\x1a\x13.greeter.HelloReply\"\x00\x62\x06proto3')



_EMPTY = DESCRIPTOR.message_types_by_name['Empty']
_HELLOREPLY = DESCRIPTOR.message_types_by_name['HelloReply']
Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'greeter_pb2'
  # @@protoc_insertion_point(class_scope:greeter.Empty)
  })
_sym_db.RegisterMessage(Empty)

HelloReply = _reflection.GeneratedProtocolMessageType('HelloReply', (_message.Message,), {
  'DESCRIPTOR' : _HELLOREPLY,
  '__module__' : 'greeter_pb2'
  # @@protoc_insertion_point(class_scope:greeter.HelloReply)
  })
_sym_db.RegisterMessage(HelloReply)

_GREETER = DESCRIPTOR.services_by_name['Greeter']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=26
  _EMPTY._serialized_end=33
  _HELLOREPLY._serialized_start=35
  _HELLOREPLY._serialized_end=64
  _GREETER._serialized_start=66
  _GREETER._serialized_end=126
# @@protoc_insertion_point(module_scope)
